name: super_app_base_flutter
description: "A base Project"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  get: ^4.6.6
  connectivity_plus: ^6.1.0
  flutter_secure_storage: ^9.2.4
  cached_network_image: ^3.4.1
  smooth_page_indicator: ^1.2.0+3
  go_router: ^14.8.0
  flutter_inappwebview: ^6.1.5
  mockito: ^5.4.5

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: IranYekan
      fonts:
        - asset: assets/fonts/iran_yekan_xfanum_regular.ttf
    - family: Modam
      fonts:
        - asset: assets/fonts/modam_fa_num_regular.ttf